Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.0.30"
  config.vm.provision "shell",
    inline: "sudo hostnamectl set-hostname node3"
  config.vm.provider :virtualbox do |vb|
    vb.name = "node3"
  end
end
